# table of contents tips: https://heymichellemac.com/table-of-contents-jekyll

# Build settings
#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
#theme: jekyll-theme-leap-day

kramdown:
  parse_block_html: true